import type { KBData } from './types';

/** Snapshot of KB for offline fallback. Generated by scripts/sync-kb.mjs */
export const BUNDLED_KB: KBData = {
  "version": "1.0.0",
  "schemaVersion": 1,
  "tokens": {
    "colors": {
      "--dasa-01": "#1A2437",
      "--dasa-02": "#BDE0F5",
      "--dasa-03": "#0037FF",
      "--dasa-04": "#65B0DD",
      "--dasa-05": "#D1C5B5",
      "--dasa-06": "#E5FF00",
      "--typeface-strong": "#161616",
      "--typeface-faded": "#4B4B4B",
      "--typeface-inverse-strong": "#FEFEFE",
      "--typeface-inverse-smooth": "#919191",
      "--neutral-light-pure": "#FFFFFF",
      "--neutral-10": "#F5F5F5",
      "--neutral-20": "#E6E6E6",
      "--neutral-dark-pure": "#18191B",
      "--neutral-dark-10": "#2B2B2B",
      "--neutral-inverse-00": "#161616",
      "--red-10": "#3B0D12",
      "--red-20": "#4F1119",
      "--red-30": "#691721",
      "--red-40": "#7E1B27",
      "--red-50": "#92202E",
      "--red-60": "#A72534",
      "--red-70": "#BC293A",
      "--red-80": "#D83145",
      "--red-90": "#EA4356",
      "--red-100": "#F55C6E",
      "--red-110": "#F77E8C",
      "--red-120": "#F895A1",
      "--red-130": "#FAAEB6",
      "--red-140": "#FBC5CC",
      "--red-150": "#FDDDE1",
      "--red-160": "#FEF1F2",
      "--yellow-10": "#321701",
      "--yellow-20": "#462101",
      "--yellow-30": "#552802",
      "--yellow-40": "#693102",
      "--yellow-50": "#7D3B03",
      "--yellow-60": "#914503",
      "--yellow-70": "#A04C03",
      "--yellow-80": "#B95804",
      "--yellow-90": "#D26404",
      "--yellow-100": "#EB7005",
      "--yellow-110": "#FA8219",
      "--yellow-120": "#FB9B46",
      "--yellow-130": "#FCB06E",
      "--yellow-140": "#FDC99B",
      "--yellow-150": "#FEE1C8",
      "--yellow-160": "#FEF1E6",
      "--gray-10": "#1F1F1F",
      "--gray-20": "#292929",
      "--gray-30": "#363636",
      "--gray-40": "#404040",
      "--gray-50": "#4C4C4C",
      "--gray-60": "#595959",
      "--gray-70": "#666666",
      "--gray-80": "#737373",
      "--gray-90": "#828282",
      "--gray-100": "#919191",
      "--gray-110": "#A1A1A1",
      "--gray-120": "#B0B0B0",
      "--gray-130": "#C2C2C2",
      "--gray-140": "#D4D4D4",
      "--gray-150": "#E6E6E6",
      "--gray-160": "#F5F5F5",
      "--green-10": "#0B2312",
      "--green-20": "#0E2F18",
      "--green-30": "#133E20",
      "--green-40": "#174A26",
      "--green-50": "#1A562C",
      "--green-60": "#1F6634",
      "--green-70": "#22723A",
      "--green-80": "#278142",
      "--green-90": "#2D954C",
      "--green-100": "#32A454",
      "--green-110": "#38B85E",
      "--green-120": "#4BC870",
      "--green-130": "#76D692",
      "--green-140": "#9DE2B1",
      "--green-150": "#C8EED3",
      "--green-160": "#E8F8EC",
      "--blue-10": "#051B48",
      "--blue-20": "#062560",
      "--blue-30": "#082F7D",
      "--blue-40": "#0A3A9A",
      "--blue-50": "#0B43B1",
      "--blue-60": "#0D4ECE",
      "--blue-70": "#0F58EA",
      "--blue-80": "#286BF1",
      "--blue-90": "#3F7BF2",
      "--blue-100": "#5C8FF5",
      "--blue-110": "#73A0F7",
      "--blue-120": "#8CB0F8",
      "--blue-130": "#A9C4F9",
      "--blue-140": "#C1D4FB",
      "--blue-150": "#D9E5FC",
      "--blue-160": "#F1F5FE",
      "--primary": "#0037FF",
      "--primary-hover": "#002FDB",
      "--primary-light": "#BDE0F5",
      "--primary-dark": "#1A2437",
      "--success": "#32A454",
      "--success-light": "#C8EED3",
      "--warning": "#EB7005",
      "--warning-light": "#FEE1C8",
      "--error": "#D83145",
      "--error-light": "#FEF1F2",
      "--info": "#3F7BF2",
      "--info-light": "#D9E5FC"
    },
    "typography": {
      "fontFamily": "Dasa Sans",
      "fontWeights": [
        400,
        500,
        700
      ],
      "fontSizes": [
        12,
        14,
        16,
        20,
        24,
        32,
        40,
        48
      ],
      "textStyles": {
        "Web/Heading/xxxl": {
          "fontWeight": 700,
          "fontSize": 48,
          "lineHeight": 1.25
        },
        "Web/Heading/xxl": {
          "fontWeight": 700,
          "fontSize": 40,
          "lineHeight": 1.25
        },
        "Web/Heading/xl": {
          "fontWeight": 700,
          "fontSize": 32,
          "lineHeight": 1.25
        },
        "Web/Heading/lg": {
          "fontWeight": 700,
          "fontSize": 24,
          "lineHeight": 1.25
        },
        "Web/Heading/md": {
          "fontWeight": 700,
          "fontSize": 20,
          "lineHeight": 1.25
        },
        "Web/Body/lg": {
          "fontWeight": 400,
          "fontSize": 16,
          "lineHeight": 1.5
        },
        "Web/Body/md": {
          "fontWeight": 400,
          "fontSize": 14,
          "lineHeight": 1.5
        },
        "Web/Body/sm": {
          "fontWeight": 400,
          "fontSize": 12,
          "lineHeight": 1.5
        }
      }
    },
    "spacing": [
      0,
      4,
      8,
      12,
      16,
      24,
      30,
      60,
      496
    ],
    "radius": [
      0,
      4,
      8,
      12,
      16,
      24,
      60,
      496
    ],
    "lineHeights": [
      1.15,
      1.2,
      1.25,
      1.33,
      1.5,
      1.7
    ],
    "borderWidths": [
      0,
      1,
      2,
      4,
      8
    ],
    "opacities": [
      0.04,
      0.08,
      0.12,
      0.24,
      0.32,
      0.56,
      0.64,
      0.72,
      0.88,
      1
    ],
    "shadowBlurs": [
      8,
      24,
      40,
      56
    ]
  },
  "copy": {
    "glossary": [
      {
        "term": "paciente",
        "use": "paciente",
        "avoid": [
          "usuário",
          "user",
          "cliente"
        ],
        "context": "Sempre usar \"paciente\" em vez de \"usuário\""
      },
      {
        "term": "convênio",
        "use": "convênio",
        "avoid": [
          "plano"
        ],
        "context": "Usar \"convênio\" em vez de \"plano\""
      },
      {
        "term": "mostrar detalhes",
        "use": "mostrar detalhes",
        "avoid": [
          "ver mais",
          "ver detalhes"
        ],
        "context": "Usar \"mostrar detalhes\" (evitar capacitismo)"
      },
      {
        "term": "ocultar detalhes",
        "use": "ocultar detalhes",
        "avoid": [
          "mostrar menos"
        ],
        "context": "Usar \"ocultar detalhes\""
      },
      {
        "term": "mostrar",
        "use": "mostrar",
        "avoid": [
          "visualizar"
        ],
        "context": "Usar \"mostrar\" em vez de \"visualizar\""
      },
      {
        "term": "fazer",
        "use": "fazer",
        "avoid": [
          "realizar"
        ],
        "context": "Usar \"fazer\" exceto tier executivo (Delboni, Alta)"
      },
      {
        "term": "querer",
        "use": "querer",
        "avoid": [
          "desejar"
        ],
        "context": "Usar \"querer\" ou \"procurar\""
      },
      {
        "term": "valores",
        "use": "valores",
        "avoid": [
          "preço",
          "price"
        ],
        "context": "Usar \"valores\" ou \"orçamento\""
      },
      {
        "term": "resultados disponíveis",
        "use": "resultados disponíveis",
        "avoid": [
          "resultados prontos",
          "resultados liberados",
          "laudo"
        ],
        "context": "Usar \"resultados disponíveis\""
      }
    ],
    "forbiddenTerms": [
      {
        "pattern": "Ver mais",
        "replacement": "Mostrar detalhes",
        "wordBoundary": false
      },
      {
        "pattern": "Ver detalhes",
        "replacement": "Mostrar detalhes",
        "wordBoundary": false
      },
      {
        "pattern": "Nav Dasa",
        "replacement": "Nav Dasa",
        "wordBoundary": false
      },
      {
        "pattern": "Erro:",
        "replacement": "",
        "wordBoundary": false
      },
      {
        "pattern": "DASA",
        "replacement": "Dasa",
        "wordBoundary": true
      },
      {
        "pattern": "NAV",
        "replacement": "Nav Dasa",
        "wordBoundary": true
      },
      {
        "pattern": "Ver",
        "replacement": "Mostrar",
        "wordBoundary": true
      },
      {
        "pattern": "Agenda",
        "replacement": "Data",
        "wordBoundary": true
      },
      {
        "pattern": "Preço",
        "replacement": "Valores",
        "wordBoundary": true
      },
      {
        "pattern": "Usuário",
        "replacement": "Paciente",
        "wordBoundary": true
      },
      {
        "pattern": "Desejar",
        "replacement": "Querer",
        "wordBoundary": true
      },
      {
        "pattern": "Realizar",
        "replacement": "Fazer",
        "wordBoundary": true
      }
    ],
    "ctaRules": {
      "length": {
        "min": 2,
        "max": 3
      },
      "noPeriod": true,
      "examples": [
        "Agendar exame",
        "Cancelar agendamento",
        "Finalizar cadastro",
        "Alterar cadastro",
        "Incluir especialidade"
      ],
      "forbidden": [
        "Continuar",
        "Próximo",
        "Avançar"
      ]
    },
    "capitalization": {
      "properNouns": [
        "Dasa",
        "Delboni",
        "Alta",
        "Nav",
        "Covid",
        "HIV",
        "Aids",
        "IST"
      ]
    }
  },
  "rules": [
    {
      "ruleId": "TOKEN_COLOR_01",
      "category": "tokens",
      "checklistItemId": "1.1",
      "severity": "HIGH",
      "title": "Cor fora do Design System",
      "description": "Cor utilizada não corresponde a nenhum token do DS",
      "check": "Comparar hex da cor com COLOR_TOKENS",
      "fix": "Aplicar cor do token mais próximo"
    },
    {
      "ruleId": "TOKEN_TYPO_01",
      "category": "tokens",
      "checklistItemId": "1.2",
      "severity": "HIGH",
      "title": "Fonte incorreta",
      "description": "Font family não é Dasa Sans",
      "check": "Verificar fontFamily do texto",
      "fix": "Aplicar Dasa Sans"
    },
    {
      "ruleId": "TOKEN_TYPO_02",
      "category": "tokens",
      "checklistItemId": "1.2",
      "severity": "MED",
      "title": "Tamanho de fonte incorreto",
      "description": "fontSize não pertence à escala do DS",
      "check": "Verificar fontSize contra escala do DS",
      "fix": "Corrigir para o tamanho mais próximo"
    },
    {
      "ruleId": "TOKEN_FONT_WEIGHT_01",
      "category": "tokens",
      "checklistItemId": "1.2",
      "severity": "MED",
      "title": "Peso de fonte incorreto",
      "description": "fontWeight não pertence ao DS (400, 500, 700)",
      "check": "Verificar fontWeight contra escala do DS",
      "fix": "Corrigir para o peso mais próximo"
    },
    {
      "ruleId": "TOKEN_LINE_HEIGHT_01",
      "category": "tokens",
      "checklistItemId": "1.2",
      "severity": "LOW",
      "title": "Entrelinha fora do padrão",
      "description": "lineHeight não pertence à escala do DS",
      "check": "Verificar lineHeight contra escala do DS",
      "fix": "Corrigir para o valor mais próximo"
    },
    {
      "ruleId": "TOKEN_RADIUS_01",
      "category": "tokens",
      "checklistItemId": "1.4",
      "severity": "LOW",
      "title": "Arredondamento incorreto",
      "description": "Corner radius não pertence ao DS",
      "check": "Comparar cornerRadius com escala do DS",
      "fix": "Corrigir para o radius mais próximo"
    },
    {
      "ruleId": "TOKEN_BORDER_WIDTH_01",
      "category": "tokens",
      "checklistItemId": "1.4",
      "severity": "LOW",
      "title": "Espessura de borda incorreta",
      "description": "strokeWeight não pertence ao DS (0, 1, 2, 4, 8px)",
      "check": "Verificar strokeWeight contra escala do DS",
      "fix": "Corrigir para o valor mais próximo"
    },
    {
      "ruleId": "TOKEN_OPACITY_01",
      "category": "tokens",
      "checklistItemId": "1.1",
      "severity": "LOW",
      "title": "Opacidade fora do padrão",
      "description": "Opacidade não pertence à escala do DS",
      "check": "Verificar opacity contra escala do DS",
      "fix": "Corrigir para o valor mais próximo"
    },
    {
      "ruleId": "TOKEN_SHADOW_01",
      "category": "tokens",
      "checklistItemId": "1.1",
      "severity": "LOW",
      "title": "Sombra fora do padrão",
      "description": "Blur da sombra não corresponde ao DS (8, 24, 40, 56px)",
      "check": "Verificar blur contra escala do DS",
      "fix": "Corrigir para o blur mais próximo"
    },
    {
      "ruleId": "TOKEN_SHADOW_BIND_01",
      "category": "tokens",
      "checklistItemId": "1.1",
      "severity": "LOW",
      "title": "Sombra sem variável vinculada",
      "description": "Sombra com valor correto mas sem vínculo à variável DS",
      "check": "Verificar se effect está vinculado à variável DS",
      "fix": "Vincular ao token de effect"
    },
    {
      "ruleId": "TOKEN_SPACING_01",
      "category": "tokens",
      "checklistItemId": "1.3",
      "severity": "MED",
      "title": "Espaçamento incorreto",
      "description": "Gap ou padding não pertence à escala de espaçamento do DS",
      "check": "Comparar gap/padding com escala do DS",
      "fix": "Corrigir para o valor mais próximo"
    },
    {
      "ruleId": "TOKEN_COLOR_BIND_01",
      "category": "tokens",
      "checklistItemId": "1.1",
      "severity": "LOW",
      "title": "Cor sem variável vinculada",
      "description": "Cor com valor correto do DS mas sem vínculo à variável",
      "check": "Verificar se fill/stroke está vinculado a color variable DS",
      "fix": "Vincular à variável DS correspondente"
    },
    {
      "ruleId": "TOKEN_SPACING_BIND_01",
      "category": "tokens",
      "checklistItemId": "1.3",
      "severity": "LOW",
      "title": "Espaçamento sem variável vinculada",
      "description": "Padding/gap com valor correto do DS mas sem vínculo à variável",
      "check": "Verificar se padding/gap está vinculado a spacing variable DS",
      "fix": "Vincular à spacing variable DS"
    },
    {
      "ruleId": "TOKEN_RADIUS_BIND_01",
      "category": "tokens",
      "checklistItemId": "1.4",
      "severity": "LOW",
      "title": "Arredondamento sem variável vinculada",
      "description": "Corner radius com valor correto do DS mas sem vínculo à variável",
      "check": "Verificar se cornerRadius está vinculado a radius variable DS",
      "fix": "Vincular à radius variable DS"
    },
    {
      "ruleId": "TOKEN_TYPO_BIND_01",
      "category": "tokens",
      "checklistItemId": "1.2",
      "severity": "LOW",
      "title": "Tipografia sem text style",
      "description": "Texto usa Dasa Sans com tamanho correto mas sem text style aplicado",
      "check": "Verificar se o nó de texto tem text style DS vinculado",
      "fix": "Aplicar o text style DS correspondente"
    },
    {
      "ruleId": "COPY_TERM_01",
      "category": "copy",
      "checklistItemId": "2.1",
      "severity": "MED",
      "title": "Termo incorreto",
      "description": "Texto usa termo que deve ser substituído conforme glossário",
      "check": "Verificar termos do glossário",
      "fix": "Aplicar termo correto"
    },
    {
      "ruleId": "COPY_TERM_02",
      "category": "copy",
      "checklistItemId": "2.4",
      "severity": "LOW",
      "title": "Capitalização incorreta",
      "description": "Título com maiúscula em palavra que não é nome próprio",
      "check": "Verificar capitalização em títulos",
      "fix": "Corrigir capitalização"
    },
    {
      "ruleId": "COPY_TERM_03",
      "category": "copy",
      "checklistItemId": "2.5",
      "severity": "HIGH",
      "title": "Termo proibido",
      "description": "Texto contém termo da lista de proibidos",
      "check": "Verificar termos proibidos",
      "fix": "Aplicar termo correto"
    },
    {
      "ruleId": "COPY_CTA_01",
      "category": "copy",
      "checklistItemId": "2.2",
      "severity": "MED",
      "title": "CTA fora do padrão",
      "description": "CTA não segue padrão: infinitivo, 2-3 palavras, sem ponto",
      "check": "Verificar padrão de CTA",
      "fix": "Reformular CTA"
    },
    {
      "ruleId": "COPY_ERROR_01",
      "category": "copy",
      "checklistItemId": "2.3",
      "severity": "MED",
      "title": "Mensagem de erro com prefixo",
      "description": "Mensagem de erro usa prefixo \"Erro:\" em vez de ser acionável",
      "check": "Verificar se texto começa com \"Erro:\"",
      "fix": "Reescrever de forma empática"
    },
    {
      "ruleId": "A11Y_TOUCH_01",
      "category": "a11y",
      "checklistItemId": "4.1",
      "severity": "BLOCKER",
      "title": "Área de toque pequena",
      "description": "Elemento interativo com dimensões abaixo do mínimo WCAG (44x44px)",
      "check": "Verificar dimensões de elementos interativos",
      "fix": "Expandir para mínimo 44x44px"
    },
    {
      "ruleId": "A11Y_CONTRAST_01",
      "category": "a11y",
      "checklistItemId": "4.2",
      "severity": "BLOCKER",
      "title": "Contraste insuficiente",
      "description": "Contraste texto/fundo abaixo de WCAG AA",
      "check": "Calcular ratio de contraste",
      "fix": "Ajustar cores para atingir ratio mínimo"
    },
    {
      "ruleId": "A11Y_IMG_ALT_01",
      "category": "a11y",
      "checklistItemId": "4.4",
      "severity": "MED",
      "title": "Imagem sem texto alternativo",
      "description": "Imagem sem description para leitores de tela",
      "check": "Verificar se imagens têm description",
      "fix": "Preencher description"
    },
    {
      "ruleId": "COMP_NAMING_01",
      "category": "components",
      "checklistItemId": "5.1",
      "severity": "LOW",
      "title": "Layer com nome genérico",
      "description": "Layer usa nome padrão do Figma (Frame, Group, Rectangle...)",
      "check": "Verificar se nome é genérico",
      "fix": "Renomear com nome semântico"
    },
    {
      "ruleId": "UX_AUTOLAYOUT_01",
      "category": "ux",
      "severity": "MED",
      "title": "Frame sem Auto Layout",
      "description": "Frame com filhos posicionados manualmente",
      "check": "Verificar autoLayoutMode",
      "fix": "Aplicar auto layout"
    }
  ],
  "checklist": [
    {
      "id": "1.1",
      "category": "tokens",
      "description": "Cores usam apenas tokens do DS",
      "weight": 1
    },
    {
      "id": "1.2",
      "category": "tokens",
      "description": "Tipografia segue hierarquia e tokens",
      "weight": 1
    },
    {
      "id": "1.3",
      "category": "tokens",
      "description": "Espaçamento segue escalas do DS",
      "weight": 0.8
    },
    {
      "id": "1.4",
      "category": "tokens",
      "description": "Border radius segue tokens",
      "weight": 0.8
    },
    {
      "id": "1.5",
      "category": "tokens",
      "description": "Componentes respeitam alturas do DS",
      "weight": 1
    },
    {
      "id": "2.1",
      "category": "copy",
      "description": "Terminologia correta",
      "weight": 1
    },
    {
      "id": "2.2",
      "category": "copy",
      "description": "CTAs em infinitivo, 2-3 palavras, sem ponto",
      "weight": 1
    },
    {
      "id": "2.3",
      "category": "copy",
      "description": "Sem \"Erro:\" como prefixo",
      "weight": 0.8
    },
    {
      "id": "2.4",
      "category": "copy",
      "description": "Maiúscula apenas na primeira palavra",
      "weight": 0.6
    },
    {
      "id": "2.5",
      "category": "copy",
      "description": "Evita palavras proibidas",
      "weight": 0.8
    },
    {
      "id": "3.1",
      "category": "ux",
      "description": "Mobile-first (375px)",
      "weight": 1
    },
    {
      "id": "3.2",
      "category": "ux",
      "description": "Uma ação principal por tela",
      "weight": 0.8
    },
    {
      "id": "3.3",
      "category": "ux",
      "description": "Labels sempre visíveis",
      "weight": 1
    },
    {
      "id": "4.1",
      "category": "a11y",
      "description": "Touch targets >= 44px",
      "weight": 1
    },
    {
      "id": "4.2",
      "category": "a11y",
      "description": "Contraste WCAG AA",
      "weight": 1
    },
    {
      "id": "4.3",
      "category": "a11y",
      "description": "Ações na thumbzone",
      "weight": 0.6
    },
    {
      "id": "5.1",
      "category": "components",
      "description": "Usa componentes oficiais",
      "weight": 1
    },
    {
      "id": "5.2",
      "category": "components",
      "description": "Sem componentes ad hoc",
      "weight": 0.8
    }
  ],
  "uxPatterns": {
    "mobileBreakpoint": 375,
    "touchTargetMin": 44
  }
};
