#!/usr/bin/env node
/**
 * Reads kb.json and generates src/kb/bundled.ts with inlined BUNDLED_KB.
 * Run from figma-plugin dir: node scripts/sync-kb.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const kbPath = path.join(root, 'kb.json');
const outPath = path.join(root, 'src', 'kb', 'bundled.ts');

const kb = JSON.parse(fs.readFileSync(kbPath, 'utf8'));
const content = `import type { KBData } from './types';

/** Snapshot of KB for offline fallback. Generated by scripts/sync-kb.mjs */
export const BUNDLED_KB: KBData = ${JSON.stringify(kb, null, 2)};
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log('Wrote', outPath);
